INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Camiseta básica', 'Ropa', 15.99, 'https://dummyimage.com/450x300.png/5fa2dd/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Pantalones vaqueros', 'Ropa', 49.99, 'https://dummyimage.com/450x300.png/ff6347/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Zapatillas deportivas', 'Calzado', 79.99, 'https://dummyimage.com/450x300.png/4682b4/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Chaqueta de cuero', 'Ropa', 99.99, 'https://dummyimage.com/450x300.png/800080/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Reloj de pulsera', 'Accesorios', 129.99, 'https://dummyimage.com/450x300.png/ff4500/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Gafas de sol', 'Accesorios', 59.99, 'https://dummyimage.com/450x300.png/2e8b57/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Mochila de senderismo', 'Deportes', 89.99, 'https://dummyimage.com/450x300.png/daa520/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Botella de agua', 'Deportes', 14.99, 'https://dummyimage.com/450x300.png/00008b/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Pelota de fútbol', 'Deportes', 29.99, 'https://dummyimage.com/450x300.png/6a5acd/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Balón de baloncesto', 'Deportes', 39.99, 'https://dummyimage.com/450x300.png/b8860b/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Bicicleta de montaña', 'Deportes', 499.99, 'https://dummyimage.com/450x300.png/8b0000/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Raqueta de tenis', 'Deportes', 69.99, 'https://dummyimage.com/450x300.png/9932cc/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Guitarra acústica', 'Instrumentos', 199.99, 'https://dummyimage.com/450x300.png/ff69b4/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Teclado electrónico', 'Instrumentos', 299.99, 'https://dummyimage.com/450x300.png/00ff7f/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Batería eléctrica', 'Instrumentos', 499.99, 'https://dummyimage.com/450x300.png/8b008b/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Micrófono de condensador', 'Instrumentos', 79.99, 'https://dummyimage.com/450x300.png/ffb6c1/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Auriculares inalámbricos', 'Electrónica', 89.99, 'https://dummyimage.com/450x300.png/7b68ee/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Smartphone', 'Electrónica', 699.99, 'https://dummyimage.com/450x300.png/00ced1/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Ordenador portátil', 'Electrónica', 999.99, 'https://dummyimage.com/450x300.png/d2691e/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Televisor 4K', 'Electrónica', 1199.99, 'https://dummyimage.com/450x300.png/ff8c00/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Cámara digital', 'Electrónica', 499.99, 'https://dummyimage.com/450x300.png/008080/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Consola de videojuegos', 'Electrónica', 399.99, 'https://dummyimage.com/450x300.png/dc143c/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Freidora de aire', 'Electrodomésticos', 129.99, 'https://dummyimage.com/450x300.png/ff1493/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Cafetera espresso', 'Electrodomésticos', 149.99, 'https://dummyimage.com/450x300.png/00bfff/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Aspiradora robótica', 'Electrodomésticos', 249.99, 'https://dummyimage.com/450x300.png/ff4500/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Ventilador de torre', 'Electrodomésticos', 59.99, 'https://dummyimage.com/450x300.png/00fa9a/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Parrilla eléctrica', 'Electrodomésticos', 99.99, 'https://dummyimage.com/450x300.png/ff6347/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Set de cuchillos de cocina', 'Hogar', 79.99, 'https://dummyimage.com/450x300.png/6b8e23/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Juego de sartenes', 'Hogar', 119.99, 'https://dummyimage.com/450x300.png/ffa500/ffffff');
INSERT INTO producto (id, nombre, categoria, precio, imagen) VALUES (NEXTVAL('producto_seq'), 'Ropa de cama', 'Hogar', 69.99, 'https://dummyimage.com/450x300.png/7fffd4/ffffff');
